kind: pipeline
type: docker
name: ci/cd
clone:
  disable: true

steps:
  - name: clone
    image: bitnami/git
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - mkdir -p $HOME/.ssh/
      - echo -n "$SSH_KEY" > $HOME/.ssh/id_ed25519
      - chmod 600 $HOME/.ssh/id_ed25519
      - touch $HOME/.ssh/known_hosts
      - chmod 600 $HOME/.ssh/known_hosts
      - touch $HOME/.ssh/config
      - chmod 600 $HOME/.ssh/config
      - echo "Host github.com\n    Hostname ssh.github.com\n    Port 443\n    User git" > $HOME/.ssh/config
      - echo "[ssh.github.com]:443 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" >> $HOME/.ssh/known_hosts
      - git config --global init.defaultBranch main
      - git init
      - git config advice.detachedHead false
      - git remote add origin $DRONE_GIT_SSH_URL
      - git fetch --no-tags --prune --no-recurse-submodules origin $DRONE_COMMIT_BRANCH
      - git checkout $DRONE_COMMIT
  - name: build
    image: registry.cn-shanghai.aliyuncs.com/zzf2001/pnpm
    depends_on: [clone]
    commands:
      - pnpm install
      - pnpm run build
  - name: oss
    image: registry.cn-shanghai.aliyuncs.com/zzf2001/drone-aliyun-oss
    depends_on: [build]
    settings:
      endpoint:
        from_secret: endpoint
      ACCESS_KEY_ID:
        from_secret: accessKeyID
      ACCESS_KEY_SECRET:
        from_secret: accessKeySecret
      BUCKET_NAME:
        from_secret: bucketName
      target: zeus
      source: ./dist
  - name: deploy
    image: appleboy/drone-scp
    depends_on: [build]
    settings:
      host:
        from_secret: caddy_host
      port: 22
      username:
        from_secret: caddy_username
      key:
        from_secret: caddy_ssh_key
#      target: /etc/caddy/zeus
#      source: ./dist
      target: /etc/caddy/${DRONE_REPO_NAME}
      source: ./dist/index.html

