kind: pipeline
volumes:
  - name: node_modules
    host:
      path: /root/zeus/node_modules
  - name: ssh_keys
    host:
      path: /root/.ssh
clone:
  disable: true

steps:
  - name: feishu
    image: registry.cn-shanghai.aliyuncs.com/zzf2001/foo-webhook
    settings:
      webhook:
        from_secret: webhook
      secret:
        from_secret: secret
      text: hello

  - name: clone
    image: alpine/git
    volumes:
      - name: ssh_keys
        path: /root/.ssh
    commands:
      - git init
      - git remote add origin $DRONE_GIT_SSH_URL
      - git fetch
      - git checkout origin/$DRONE_COMMIT_BRANCH -ft


  - name: build
    image: node
    depends_on: [clone]
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
    commands:
      - pwd
      - ls -a
      - npm install
      - npm run build
  - name: oss
    image: registry.cn-shanghai.aliyuncs.com/zzf2001/drone-aliyun-oss
    depends_on: [build]
    settings:
      endpoint:
        from_secret: endpoint
      ACCESS_KEY_ID:
        from_secret: accessKeyID
      ACCESS_KEY_SECRET:
        from_secret: accessKeySecret
      BUCKET_NAME:
        from_secret: bucketName
      target: zeus
      source: ./dist
  - name: deploy
    image: appleboy/drone-scp
    depends_on: [build]
    settings:
      host:
        from_secret: host
      port: 22
      username:
        from_secret: username
      password:
        from_secret: password
      target: /root/www/zeus.zzfzzf.com
      source: ./dist
